name: Deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:

  build:
    name: Build & Deploy on Surge.sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 13.11.0
      - run: yarn install
      - run: yarn build
      - run: cp ./dist/index.html ./dist/200.html
      - run: mkdir ./dist/.well_known
      - run: cp ./public/apple-app-site-association ./dist/apple-app-site-association.json
      - run: ./node_modules/.bin/surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
